Team.create!(name: %q(Bills, Buffalo), abrv: 'BUF')
Team.create!(name: %q(Colts, Indianapolis), abrv: 'IND')
Team.create!(name: %q(Dolphins, Miami), abrv: 'MIA')
Team.create!(name: %q(Patriots, New England), abrv: 'NEP')
Team.create!(name: %q(Jets, New York), abrv: 'NYJ')
Team.create!(name: %q(Bengals, Cincinnati), abrv: 'CIN')
Team.create!(name: %q(Browns, Cleveland), abrv: 'CLE')
Team.create!(name: %q(Titans, Tennessee), abrv: 'TEN')
Team.create!(name: %q(Jaguars, Jacksonville), abrv: 'JAC')
Team.create!(name: %q(Steelers, Pittsburgh), abrv: 'PIT')
Team.create!(name: %q(Broncos, Denver), abrv: 'DEN')
Team.create!(name: %q(Chiefs, Kansas City), abrv: 'KCC')
Team.create!(name: %q(Raiders, Oakland), abrv: 'OAK')
Team.create!(name: %q(Chargers, San Diego), abrv: 'SDC')
Team.create!(name: %q(Seahawks, Seattle), abrv: 'SEA')
Team.create!(name: %q(Cowboys, Dallas), abrv: 'DAL')
Team.create!(name: %q(Giants, New York), abrv: 'NYG')
Team.create!(name: %q(Eagles, Philadelphia), abrv: 'PHI')
Team.create!(name: %q(Cardinals, Arizona), abrv: 'ARI')
Team.create!(name: %q(Redskins, Washington), abrv: 'WAS')
Team.create!(name: %q(Bears, Chicago), abrv: 'CHI')
Team.create!(name: %q(Lions, Detroit), abrv: 'DET')
Team.create!(name: %q(Packers, Green Bay), abrv: 'GBP')
Team.create!(name: %q(Vikings, Minnesota), abrv: 'MIN')
Team.create!(name: %q(Buccaneers, Tampa Bay), abrv: 'TBB')
Team.create!(name: %q(Falcons, Atlanta), abrv: 'ATL')
Team.create!(name: %q(Panthers, Carolina), abrv: 'CAR')
Team.create!(name: %q(Rams, St. Louis), abrv: 'STL')
Team.create!(name: %q(Saints, New Orleans), abrv: 'NOS')
Team.create!(name: %q(49ers, San Francisco), abrv: 'SFO')
Team.create!(name: %q(Ravens, Baltimore), abrv: 'BAL')
Team.create!(name: %q(Texans, Houston), abrv: 'HOU')
